### ISSUE TITLE
sudo sh boot.sh init  报错 

### ISSUE THREAD

**Issue by lxj5891** [istoreos/istoreos-kvm#1]
RTNETLINK answers: File exists
RTNETLINK answers: File exists
net.ipv6.conf.br-iso0.disable_ipv6 = 1
net.ipv6.conf.br-iso1.disable_ipv6 = 1
net.ipv4.ip_forward = 1
boot.sh: 13: ./firewall.sh: Permission denied
Error: ipv4: Address already assigned.
Error: ipv4: Address already assigned.
error: failed to get domain 'istoreos'

**Comment by jjm2473** [comment]
不知道你这是干啥的命令，`./firewall.sh: Permission denied`意思是firewall.sh没有可执行权限，要用chmod加上权限。

哦，确实项目的文件没加权限，现在加上。
